//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum_Task_Board.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int cardID { get; set; }
        [Range(1,100000,ErrorMessage = "1 ve 100000 aralýðýnda rakamlar girebilirsiniz!")]
        [Required(ErrorMessage = "Deðer girmeniz gerek!")]
        public int cardNo { get; set; }
        public System.DateTime cardCreationDate { get; set; }
        public string cardEstimatedTime { get; set; }
        public string cardActualTime { get; set; }
        [StringLength(400,ErrorMessage = "En fazla 400 karakter uzunluðunda karakter girebilirsiniz.")]
        [Required(ErrorMessage = "Deðer girmeniz gerek!")]
        public string cardName { get; set; }
        [StringLength(2000, ErrorMessage = "En fazla 2000 karakter uzunluðunda karakter girebilirsiniz.")]
        [Required(ErrorMessage = "Deðer girmeniz gerek!")]
        public string cardDefinition { get; set; }
        [StringLength(2000, ErrorMessage = "En fazla 2000 karakter uzunluðunda karakter girebilirsiniz.")]
        [Required(ErrorMessage = "Deðer girmeniz gerek!")]
        public string cardNotes { get; set; }
        [StringLength(50, ErrorMessage = "En fazla 50 karakter uzunluðunda karakter girebilirsiniz."), MinLength(2, ErrorMessage = "En az 2 karakter girmeniz gerekmektedir!")]
        [Required(ErrorMessage = "Deðer girmeniz gerek!")]
        public string cardExpert { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
    }
}
