//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum_Task_Board.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        public int taskID { get; set; }
        [DisplayName("Ýþ Tarihi: "),
        DisplayFormat(DataFormatString = "{yyyy-MM-dd HH:mm:ss.fff}")]
        public System.DateTime taskDate { get; set; }
        [StringLength(2000, ErrorMessage = "En fazla 2000 karakter uzunluðunda karakter girebilirsiniz.")]
        public string taskHeader { get; set; }
        [StringLength(2000, ErrorMessage = "En fazla 2000 karakter uzunluðunda karakter girebilirsiniz.")]
        public string taskDefinition { get; set; }
        public int taskStateID { get; set; }
        public int cardID { get; set; }
        public virtual Card Card { get; set; }
        public virtual State State { get; set; }
    }
}
